### ISSUE TITLE
I2C initialize problem

### ISSUE THREAD

**Issue by narise77** [ondryaso/pi-ssd1306-java#2]
<pre>
-        Field f = this.i2c.getClass().getDeclaredField("fd");
-        f.setAccessible(true);
-        this.fd = f.getInt(this.i2c);

+      this.fd = I2C.wiringPiI2CSetup(address);
+      if ( this.fd == -1 ){
+       	throw new IOException("Unable to open device at address: " + address);
+      }

</pre>

**Comment by mkattner** [comment]
java.lang.NoSuchFieldException: fd
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at eu.ondryaso.ssd1306.Display.<init>(Display.java:72)
	at eu.ondryaso.ssd1306.Display.<init>(Display.java:106)

**Comment by ShisanXing** [comment]
try i2c.write() instead ? fd is belong to LinuxFile (from RandomAccessFile) not I2cDevice.
